# Generated by Django 3.1.6 on 2021-02-11 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='visitor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=40)),
                ('Temperature', models.DecimalField(decimal_places=2, max_digits=10)),
                ('Company', models.CharField(max_length=40)),
                ('user_id', models.IntegerField(null=True)),
                ('Telephone', models.CharField(max_length=13)),
                ('Date_created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
