# Generated by Django 3.1.6 on 2021-02-11 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkin', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='visitor',
            name='user_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
